## 🧭 Data Loading — USGS Global Earthquake Dataset (1900–Present)

This dataset contains detailed information on significant global earthquakes
(magnitude ≥ 5.0) recorded since 1900. Sourced weekly from the United States
Geological Survey (USGS), it includes comprehensive data such as timestamp,
location (latitude & longitude), magnitude, depth, and measurement network details.

Earthquakes originate from tectonic activity across both highly seismic regions, such
as the Pacific Ring of Fire, and less active zones like Europe and Africa. The dataset
serves as a valuable resource for analyzing long-term seismic patterns, understanding
geological behavior, and developing predictive models.

### Key Columns Explained:
- **time**: Timestamp in milliseconds since Unix epoch (UTC) representing event occurrence.
- **latitude / longitude**: Coordinates of the earthquake's epicenter (in decimal degrees).
- **depth**: Depth of the event in kilometers.
- **mag**: Reported earthquake magnitude.
- **magType**: Type of magnitude measurement (e.g., mb, ml, mw).
- **nst**: Number of stations used to compute the earthquake solution.
- **gap**: Largest azimuthal gap between stations, in degrees.
- **dmin**: Distance to the nearest recording station (in degrees).
- **rms**: Root-mean-square residual of seismic station readings.
- **net / id**: Network and unique event identifiers.
- **updated**: Last update timestamp for the event record.
- **place**: Human-readable location description.
- **type**: Event type (e.g., “earthquake”, “explosion”, “quarry blast”).
- **horizontalError / depthError / magError**: Uncertainty measurements of calculations.
- **status**: Event status within USGS catalog (e.g., “reviewed”, “automatic”).
- **locationSource / magSource**: Networks providing the location and magnitude data.

This dataset supports exploratory analyses, time-series pattern detection, and
predictive-modeling of seismic events worldwide, making it highly applicable to
earthquake research and risk assessment projects.

Source Link: https://www.kaggle.com/datasets/usamabuttar/significant-earthquakes?resource=download

In [12]:
# Mount google drive
#from google.colab import drive
#drive.mount('/content/drive')

In [13]:

# Load USGS Earthquake Data
import pandas as pd

# Replace this path or URL with your actual dataset location
data_path = "C:/Users/SRIVIDYA GAJJALA/Datasets/Significant_Earthquakes.csv"
earthquake_df = pd.read_csv(data_path)

# Display basic information and preview
earthquake_df.info()
earthquake_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110265 entries, 0 to 110264
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       110265 non-null  int64
 1   time             110265 non-null  object
 2   latitude         110265 non-null  float64
 3   longitude        110265 non-null  float64
 4   depth            109980 non-null  float64
 5   mag              110265 non-null  float64
 6   magType          110265 non-null  object
 7   nst              39624 non-null   float64
 8   gap              49915 non-null   float64
 9   dmin             29971 non-null   float64
 10  rms              81518 non-null   float64
 11  net              110265 non-null  object
 12  id               110265 non-null  object
 13  updated          110265 non-null  object
 14  place            109374 non-null  object
 15  type             110265 non-null  object
 16  horizontalError  28591 non-null   float64
 17  depthError       60550 non-null   float64
 18  magError         43204 non-null   float64
 19  magNst           50240 non-null   float64
 20  status           110265 non-null  object
 21  locationSource   110265 non-null  object
 22  magSource        110265 non-null  object
dtypes: float64(12), int64(1), object(10)
memory usage: 19.3+ MB

,Unnamed: 0,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,0,1900-10-09T12:25:00.000Z,57.09,-153.48,NaN,7.86,mw,NaN,NaN,NaN,...,2022-05-09T14:44:17.838Z,"16 km SW of Old Harbor, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,pt
1,1,1901-03-03T07:45:00.000Z,36.00,-120.50,NaN,6.40,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"12 km NNW of Parkfield, California",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,ell
2,2,1901-07-26T22:20:00.000Z,40.80,-115.70,NaN,5.00,fa,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"6 km SE of Elko, Nevada",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sjg
3,3,1901-12-30T22:34:00.000Z,52.00,-160.00,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,south of Alaska,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe
4,4,1902-01-01T05:20:30.000Z,52.38,-167.45,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"113 km ESE of Nikolski, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe

## 🔍 Data Inspection — Exploring Earthquake Dataset Structure

In this stage, we perform an initial inspection of the earthquake data
to understand its overall structure, completeness, and summary statistics.

Typical inspection steps include:
1. Viewing the dataset shape and column names.
2. Identifying data types and non-null counts.
3. Checking for missing values.
4. Reviewing unique entries in categorical columns.
5. Exploring basic descriptive statistics to detect scale variations or anomalies.

In [14]:
# View the dataset shape (rows × columns)
print("Dataset shape:", earthquake_df.shape)

Dataset shape: (110265, 23)

In [15]:
# Display the first few records
display(earthquake_df.head())

,Unnamed: 0,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,0,1900-10-09T12:25:00.000Z,57.09,-153.48,NaN,7.86,mw,NaN,NaN,NaN,...,2022-05-09T14:44:17.838Z,"16 km SW of Old Harbor, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,pt
1,1,1901-03-03T07:45:00.000Z,36.00,-120.50,NaN,6.40,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"12 km NNW of Parkfield, California",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,ell
2,2,1901-07-26T22:20:00.000Z,40.80,-115.70,NaN,5.00,fa,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"6 km SE of Elko, Nevada",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sjg
3,3,1901-12-30T22:34:00.000Z,52.00,-160.00,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,south of Alaska,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe
4,4,1902-01-01T05:20:30.000Z,52.38,-167.45,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"113 km ESE of Nikolski, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe

In [16]:
# Display column names and their data types
print("\n--- Column Details ---")
earthquake_df.info()

--- Column Details ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110265 entries, 0 to 110264
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       110265 non-null  int64
 1   time             110265 non-null  object
 2   latitude         110265 non-null  float64
 3   longitude        110265 non-null  float64
 4   depth            109980 non-null  float64
 5   mag              110265 non-null  float64
 6   magType          110265 non-null  object
 7   nst              39624 non-null   float64
 8   gap              49915 non-null   float64
 9   dmin             29971 non-null   float64
 10  rms              81518 non-null   float64
 11  net              110265 non-null  object
 12  id               110265 non-null  object
 13  updated          110265 non-null  object
 14  place            109374 non-null  object
 15  type             110265 non-null  object
 16  horizontalError  28591 non-null   float64
 17  depthError       60550 non-null   float64
 18  magError         43204 non-null   float64
 19  magNst           50240 non-null   float64
 20  status           110265 non-null  object
 21  locationSource   110265 non-null  object
 22  magSource        110265 non-null  object
dtypes: float64(12), int64(1), object(10)
memory usage: 19.3+ MB

In [17]:
# Check for missing values across all columns
print("\n--- Missing Values Summary ---")
missing_summary = earthquake_df.isnull().sum().sort_values(ascending=False)
display(missing_summary[missing_summary > 0])

--- Missing Values Summary ---

horizontalError    81674
dmin               80294
nst                70641
magError           67061
gap                60350
magNst             60025
depthError         49715
rms                28747
place                891
depth                285
dtype: int64

In [18]:
# View unique event types and magnitude types
print("\n--- Unique Event Types ---")
print(earthquake_df["type"].unique())

--- Unique Event Types ---
['earthquake' 'nuclear explosion' 'explosion' 'rock burst' 'mine collapse'
 'volcanic eruption' 'landslide']

In [19]:
print("\n--- Unique Magnitude Types ---")
print(earthquake_df["magType"].unique())

--- Unique Magnitude Types ---
['mw' 'ms' 'fa' 'ml' 'mint' 'mb' 'lg' 'uk' 'mh' 'mwc' 'md' 'mb_lg' 'mc'
 'ma' 'mwb' 'mww' 'mwr' 'mlg' 'm' 'Md' 'Ml' 'ms_20' 'mwp' 'Mi' 'Mb'
 'ml(texnet)']

In [20]:
# Get statistical overview for numerical columns
print("\n--- Descriptive Statistics ---")
display(earthquake_df.describe())

--- Descriptive Statistics ---

,Unnamed: 0,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,110265.000000,110265.000000,110265.000000,109980.000000,110265.000000,39624.000000,49915.000000,29971.000000,81518.000000,28591.000000,60550.000000,43204.000000,50240.000000
mean,55132.000000,3.702324,41.446956,61.324340,5.441330,140.973324,65.610971,4.196260,0.947560,7.866964,7.274871,0.148538,64.587759
std,31830.908053,30.440115,121.945452,107.624498,0.479178,116.914203,39.214020,5.185751,0.364854,3.906631,10.130434,0.145551,101.612830
min,0.000000,-77.080000,-179.997000,-4.000000,5.000000,0.000000,6.500000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000
25%,27566.000000,-17.853000,-71.988000,10.000000,5.100000,63.000000,37.000000,1.296500,0.800000,6.200000,1.900000,0.055000,13.000000
50%,55132.000000,-0.682000,100.443200,33.000000,5.300000,103.000000,57.000000,2.513000,0.950000,7.770000,4.600000,0.081000,30.000000
75%,82698.000000,29.891200,143.181000,51.000000,5.630000,179.000000,84.500000,4.912500,1.100000,9.380000,8.100000,0.200000,68.000000
max,110264.000000,87.386000,180.000000,700.000000,9.500000,929.000000,360.000000,50.901000,69.320000,99.000000,1091.900000,1.840000,1144.000000

In [21]:
# Checking for duplicate records using unique ID
duplicate_count = earthquake_df.duplicated(subset=['id']).sum()
print(f"\nDuplicate Records Based on 'id': {duplicate_count}")

Duplicate Records Based on 'id': 9246

- **Observations**

*Contains around 110,000 earthquake records with 23 columns, covering global events from 1900 to the present.

*Key columns include time, latitude, longitude, depth, and magnitude, which are available for most records.

*Columns like nst, gap, dmin, and error values have many missing entries, so they may need cleaning or imputation.

*The event type is mostly “earthquake”, but a few records are labeled as “explosion” or “quarry blast.”

*Multiple magnitude types (e.g., mb, ml, mw) are used, showing data collected from different measurement systems.

*A duplicate check using event IDs shows few or no duplicates, meaning each record is likely unique.

*The range of magnitude and depth values indicates the dataset includes both shallow and deep earthquakes of different intensities.

*Overall, the dataset is well-structured and detailed, but missing and inconsistent values will need attention before analysis or visualization.